title: default-blueprint
image:
  back: 'var(--theme-primary)'
  color: 'var(--theme-accent)'

tabs:
  content:
    label: content
    icon: text
    columns:
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
              blocks: fields/blocks
      sidebar:
        width: 1/3
        sections:
          pages:
            type: pages
            template: default

